services:
  api1:
    image: avsi_proxy
    container_name: api1
    networks:
      - api_network

  api2:
    image: avsi_proxy
    container_name: api2
    networks:
      - api_network

  api3:
    image: avsi_proxy
    container_name: api3
    networks:
      - api_network



networks:
  api_network:
    driver: bridge 